### ISSUE TITLE
ASUS UX305 - other ali values

### ISSUE THREAD

**Issue by Perlover** [danieleds/Asus-Zenbook-Ambient-Light-Sensor-Controller#25]
Hi,

I have Asus UX305
I see other max & min values of file  /sys/bus/acpi/devices/ACPI0008:00/ali (to see getAmbientLightPercent function)

For example my normal lightning in room i see there values as 1457-1469 thah in hax is 0x5b1-0x5bd

If i light by lantern in sencor i see there values as 17965 for example (0x462d)

**Comment by Perlover** [comment]
I made some fixes for Asus UX305 ONLY
For me it's confortable
The brightness to be corrected from 10-100%
https://github.com/Perlover/Asus-Zenbook-Ambient-Light-Sensor-Controller/tree/asus-ux305
I don't know now how to make common patch for all notebooks types...

**Comment by danieleds** [comment]
Thank you!
Have you been able to get the explicit min and max values from the sensor? Are they stated somewhere?

If not, we should consider adding an heuristic so that the minimum and maximum values are inferred over time, and the proportion is adjusted accordingly.
What do you think?

**Comment by Perlover** [comment]
Hi,
I don't have a Asus UX305 now near from me
But i remember that there are no max & min values in some /proc files
I found theirs in tests - min 0, max 22000-26000.
And now i use your patched repo - https://github.com/Perlover/Asus-Zenbook-Ambient-Light-Sensor-Controller/tree/asus-ux305 - and everything works now fine. :)

**Comment by danieleds** [comment]
Ok! So a good heuristic would work.
Thanks for your help! :)

**Comment by danieleds** [comment]
Opened a new issue to address this (#26)
